Search.appendIndex(
    [
                {
            "fqsen": "\\UploadThing\\HttpClient",
            "name": "HttpClient",
            "summary": "",
            "url": "classes/UploadThing-HttpClient.html"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-HttpClient.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "The\u0020function\u0020\u0022request\u0022\u0020sends\u0020an\u0020HTTP\u0020request\u0020using\u0020the\u0020specified\u0020method,\u0020path,\u0020and\u0020options.",
            "url": "classes/UploadThing-HttpClient.html#method_request"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003AgenerateUrl\u0028\u0029",
            "name": "generateUrl",
            "summary": "The\u0020function\u0020generates\u0020a\u0020URL\u0020by\u0020concatenating\u0020the\u0020host\u0020and\u0020the\u0020given\u0020path.",
            "url": "classes/UploadThing-HttpClient.html#method_generateUrl"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003AUT_VERSION",
            "name": "UT_VERSION",
            "summary": "",
            "url": "classes/UploadThing-HttpClient.html#constant_UT_VERSION"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003AHOST",
            "name": "HOST",
            "summary": "",
            "url": "classes/UploadThing-HttpClient.html#constant_HOST"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/UploadThing-HttpClient.html#property_headers"
        },                {
            "fqsen": "\\UploadThing\\HttpClient\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/UploadThing-HttpClient.html#property_client"
        },                {
            "fqsen": "\\UploadThing\\Utils",
            "name": "Utils",
            "summary": "",
            "url": "classes/UploadThing-Utils.html"
        },                {
            "fqsen": "\\UploadThing\\Utils\u003A\u003AwithExponentialBackoff\u0028\u0029",
            "name": "withExponentialBackoff",
            "summary": "The\u0020function\u0020\u0060withExponentialBackoff\u0060\u0020retries\u0020a\u0020given\u0020callback\u0020function\u0020with\u0020an\u0020increasing\u0020delay\nbetween\u0020retries,\u0020up\u0020to\u0020a\u0020maximum\u0020number\u0020of\u0020retries\u0020and\u0020maximum\u0020delay\u0020time.",
            "url": "classes/UploadThing-Utils.html#method_withExponentialBackoff"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileListEntry",
            "name": "FileListEntry",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileListEntry.html"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileListEntry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileListEntry.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileListEntry\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileListEntry.html#property_id"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileListEntry\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileListEntry.html#property_key"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FilesList",
            "name": "FilesList",
            "summary": "",
            "url": "classes/UploadThing-Structs-FilesList.html"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FilesList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-Structs-FilesList.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FilesList\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/UploadThing-Structs-FilesList.html#method_fromArray"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FilesList\u003A\u003A\u0024files",
            "name": "files",
            "summary": "",
            "url": "classes/UploadThing-Structs-FilesList.html#property_files"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FilesList\u003A\u003A\u0024hasMore",
            "name": "hasMore",
            "summary": "",
            "url": "classes/UploadThing-Structs-FilesList.html#property_hasMore"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileUrlList",
            "name": "FileUrlList",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileUrlList.html"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileUrlList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileUrlList.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileUrlList\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileUrlList.html#method_fromArray"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileUrlList\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileUrlList.html#property_key"
        },                {
            "fqsen": "\\UploadThing\\Structs\\FileUrlList\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/UploadThing-Structs-FileUrlList.html#property_url"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadedData",
            "name": "UploadedData",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadedData.html"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadedData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadedData.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadedData\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadedData.html#property_key"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadedData\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadedData.html#property_url"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadedData\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadedData.html#property_name"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadedData\u003A\u003A\u0024size",
            "name": "size",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadedData.html#property_size"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadThingException",
            "name": "UploadThingException",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadThingException.html"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadThingException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadThingException.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadThingException\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadThingException.html#method_fromResponse"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadThingException\u003A\u003AgetErrorCodeFromStatus\u0028\u0029",
            "name": "getErrorCodeFromStatus",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadThingException.html#method_getErrorCodeFromStatus"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UploadThingException\u003A\u003AERROR_CODES",
            "name": "ERROR_CODES",
            "summary": "",
            "url": "classes/UploadThing-Structs-UploadThingException.html#constant_ERROR_CODES"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo",
            "name": "UsageInfo",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#method_fromArray"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024totalBytes",
            "name": "totalBytes",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_totalBytes"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024totalReadable",
            "name": "totalReadable",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_totalReadable"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024appTotalBytes",
            "name": "appTotalBytes",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_appTotalBytes"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024appTotalReadable",
            "name": "appTotalReadable",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_appTotalReadable"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024filesUploaded",
            "name": "filesUploaded",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_filesUploaded"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024limitBytes",
            "name": "limitBytes",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_limitBytes"
        },                {
            "fqsen": "\\UploadThing\\Structs\\UsageInfo\u003A\u003A\u0024limitReadable",
            "name": "limitReadable",
            "summary": "",
            "url": "classes/UploadThing-Structs-UsageInfo.html#property_limitReadable"
        },                {
            "fqsen": "\\UploadThing\\UploadThing",
            "name": "UploadThing",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#method___construct"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "The\u0020function\u0020\u0060upload\u0060\u0020takes\u0020in\u0020one\u0020or\u0020multiple\u0020files,\u0020along\u0020with\u0020optional\u0020metadata\u0020and\u0020content\ndisposition,\u0020and\u0020uploads\u0020them\u0020to\u0020a\u0020server\u0020using\u0020a\u0020POST\u0020request.",
            "url": "classes/UploadThing-UploadThing.html#method_upload"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003AdeleteFiles\u0028\u0029",
            "name": "deleteFiles",
            "summary": "The\u0020function\u0020\u0060deleteFiles\u0060\u0020deletes\u0020one\u0020or\u0020more\u0020files\u0020by\u0020sending\u0020a\u0020POST\u0020request\u0020to\u0020an\u0020API\nendpoint\u0020and\u0020returns\u0020the\u0020response\u0020as\u0020JSON.",
            "url": "classes/UploadThing-UploadThing.html#method_deleteFiles"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003AlistFiles\u0028\u0029",
            "name": "listFiles",
            "summary": "The\u0020function\u0020\u0060listFiles\u0060\u0020sends\u0020a\u0020request\u0020to\u0020the\u0020\u0060\/api\/listFiles\u0060\u0020endpoint\u0020with\u0020optional\u0020limit\nand\u0020offset\u0020parameters\u0020to\u0020retrieve\u0020a\u0020list\u0020of\u0020files.",
            "url": "classes/UploadThing-UploadThing.html#method_listFiles"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003ArenameFiles\u0028\u0029",
            "name": "renameFiles",
            "summary": "The\u0020function\u0020\u0060renameFiles\u0060\u0020sends\u0020a\u0020request\u0020to\u0020rename\u0020files\u0020using\u0020the\u0020provided\u0020updates\u0020and\nreturns\u0020an\u0020error\u0020message\u0020if\u0020an\u0020unknown\u0020error\u0020occurs.",
            "url": "classes/UploadThing-UploadThing.html#method_renameFiles"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003AgetFileUrls\u0028\u0029",
            "name": "getFileUrls",
            "summary": "The\u0020getFileUrls\u0020function\u0020takes\u0020in\u0020a\u0020string\u0020or\u0020an\u0020array\u0020of\u0020file\u0020keys\u0020and\u0020returns\u0020the\u0020file\u0020URLs.",
            "url": "classes/UploadThing-UploadThing.html#method_getFileUrls"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003AgetUsageInfo\u0028\u0029",
            "name": "getUsageInfo",
            "summary": "The\u0020function\u0020retrieves\u0020usage\u0020information\u0020from\u0020an\u0020API\u0020and\u0020returns\u0020it\u0020as\u0020a\u0020UsageInfo\u0020object.",
            "url": "classes/UploadThing-UploadThing.html#method_getUsageInfo"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003ArequestUT\u0028\u0029",
            "name": "requestUT",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#method_requestUT"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003AuploadFile\u0028\u0029",
            "name": "uploadFile",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#method_uploadFile"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003ApollForFileData\u0028\u0029",
            "name": "pollForFileData",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#method_pollForFileData"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003AuploadPart\u0028\u0029",
            "name": "uploadPart",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#method_uploadPart"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003A\u0024http",
            "name": "http",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#property_http"
        },                {
            "fqsen": "\\UploadThing\\UploadThing\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "",
            "url": "classes/UploadThing-UploadThing.html#property_apiKey"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\UploadThing",
            "name": "UploadThing",
            "summary": "",
            "url": "namespaces/uploadthing.html"
        },                {
            "fqsen": "\\UploadThing\\Structs",
            "name": "Structs",
            "summary": "",
            "url": "namespaces/uploadthing-structs.html"
        }            ]
);
