name: Release
on:
  release:
    types: [released]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  phpdoc:
    name: PHPDoc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Download PHPDoc
        run: wget https://phpdoc.org/phpDocumentor.phar

      - name: Generate PHPDoc
        run: php phpDocumentor.phar run -d src -t docs

      - name: Deploy PHPDoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
